spring.application.name=training
spring.datasource.url=jdbc:postgresql://localhost:5433/capacitacion
spring.datasource.username=trinidad
spring.datasource.password=capacitacion123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
jwt.secret=clave-secret-de-la-capacitacion-para-firmar-tokens-labo2
jwt.expiration-ms=86400000
logging.level.edu.studyarena.training.security=DEBUG